# Generated by Django 3.1.2 on 2020-11-02 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('nome', models.CharField(max_length=100)),
                ('rg', models.IntegerField()),
                ('cpf', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('telefone', models.IntegerField()),
                ('descricao', models.CharField(blank=True, max_length=3000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('paleto_barra', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calca_barra', models.DecimalField(decimal_places=2, max_digits=5)),
                ('torax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('costas', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('Pronto', 'Pronto'), ('Aguardando', 'Aguardando')], max_length=100)),
                ('data_entrega', models.DateTimeField()),
                ('medidas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='controle.ficha')),
            ],
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Traje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
                ('modelo', models.CharField(max_length=80)),
                ('corte', models.CharField(max_length=80)),
                ('quantidade', models.IntegerField()),
                ('quantidade_disponivel', models.IntegerField(null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_locacao', models.DateTimeField()),
                ('data_devolucao', models.DateTimeField()),
                ('status', models.CharField(choices=[('Alocado', 'Alocado'), ('Devolvido', 'Devolvido'), ('Atraso', 'Em Atraso')], max_length=100)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.contrato')),
                ('item', models.ManyToManyField(to='controle.Item')),
                ('lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.lancamento')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='traje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.traje'),
        ),
    ]
