# Generated by Django 3.1.2 on 2021-02-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traje',
            name='ativo',
            field=models.CharField(choices=[(0, 'Não'), (1, 'Sim')], default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='traje',
            name='codigo',
            field=models.CharField(default='victorlindao', max_length=20),
        ),
    ]
