# Generated by Django 3.1.2 on 2021-02-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0003_auto_20210226_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traje',
            name='codigo',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
