# Generated by Django 2.1.7 on 2021-03-14 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0004_auto_20210226_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='traje',
            name='ativo',
            field=models.CharField(choices=[('nao', 'Não'), ('sim', 'Sim')], default='sim', max_length=100),
        ),
    ]
