# Generated by Django 3.2 on 2021-05-10 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0007_auto_20210410_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='documento_externo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rg',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='status',
            field=models.CharField(choices=[('Alocado', 'Alocado'), ('Devolvido', 'Devolvido'), ('Atraso', 'Em Atraso'), ('Cancelado', 'Cancelado')], max_length=100),
        ),
    ]
