# Generated by Django 3.2 on 2021-05-23 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0009_alter_cliente_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=3000)),
                ('mensagem', models.CharField(max_length=3000)),
                ('destinatario', models.CharField(max_length=3000)),
            ],
        ),
    ]
